//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Player/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace TopDownShooter
{
    public partial class @NewControls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @NewControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""NewActionMap"",
            ""id"": ""939c221f-f6c2-4aab-a6a7-cc6f56159810"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""50312170-34d1-429b-94ed-cc45145070a0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseLook"",
                    ""type"": ""Value"",
                    ""id"": ""0c42f34a-36d1-4e55-96f2-0fc66e7a3138"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SimpleShoot"",
                    ""type"": ""Button"",
                    ""id"": ""a2b86419-e716-4f61-b205-97b28b2b4d8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AlternativeShoot"",
                    ""type"": ""Button"",
                    ""id"": ""c5aba828-c251-491f-86db-fa1e829aa455"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Active Flashlight"",
                    ""type"": ""Button"",
                    ""id"": ""dd253e64-515e-4772-95c4-7227f0764e30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadGun"",
                    ""type"": ""Button"",
                    ""id"": ""1a861015-edd8-42ec-be26-37669a39448c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""992b7198-d2bc-4177-889a-ef79c0640141"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveTasksMenu"",
                    ""type"": ""Button"",
                    ""id"": ""51a998cf-e46f-41dd-a453-89b340aa7da4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""af9067dc-86a6-42ae-8406-0cb3da79b6e0"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ef71f252-c266-4504-9c71-097b193f1a0b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1242bdba-e3e9-4b90-9a9d-2fca7c99db98"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c71a340e-28ef-4794-a778-a3baec930e10"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9d260660-ecc1-4b68-8710-6b62424a453e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5a9ece57-3714-476b-8f96-9547b07840e5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""72056b17-0a7d-4213-9b88-1dee38c8aed5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SimpleShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d0ccf44-e3b4-46e3-847a-80e5eecb538b"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AlternativeShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75dfd7ef-2438-4e20-980f-41e9ab2dbb8f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Active Flashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29fb2b96-1a8c-4762-b93c-9e832a0f4a9c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86af79bb-997d-4f83-9dbc-3089ce36e72a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a0ae26d-cdf6-424c-afce-f9568eef04f4"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveTasksMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // NewActionMap
            m_NewActionMap = asset.FindActionMap("NewActionMap", throwIfNotFound: true);
            m_NewActionMap_Movement = m_NewActionMap.FindAction("Movement", throwIfNotFound: true);
            m_NewActionMap_MouseLook = m_NewActionMap.FindAction("MouseLook", throwIfNotFound: true);
            m_NewActionMap_SimpleShoot = m_NewActionMap.FindAction("SimpleShoot", throwIfNotFound: true);
            m_NewActionMap_AlternativeShoot = m_NewActionMap.FindAction("AlternativeShoot", throwIfNotFound: true);
            m_NewActionMap_ActiveFlashlight = m_NewActionMap.FindAction("Active Flashlight", throwIfNotFound: true);
            m_NewActionMap_ReloadGun = m_NewActionMap.FindAction("ReloadGun", throwIfNotFound: true);
            m_NewActionMap_ChangeWeapon = m_NewActionMap.FindAction("ChangeWeapon", throwIfNotFound: true);
            m_NewActionMap_ActiveTasksMenu = m_NewActionMap.FindAction("ActiveTasksMenu", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // NewActionMap
        private readonly InputActionMap m_NewActionMap;
        private INewActionMapActions m_NewActionMapActionsCallbackInterface;
        private readonly InputAction m_NewActionMap_Movement;
        private readonly InputAction m_NewActionMap_MouseLook;
        private readonly InputAction m_NewActionMap_SimpleShoot;
        private readonly InputAction m_NewActionMap_AlternativeShoot;
        private readonly InputAction m_NewActionMap_ActiveFlashlight;
        private readonly InputAction m_NewActionMap_ReloadGun;
        private readonly InputAction m_NewActionMap_ChangeWeapon;
        private readonly InputAction m_NewActionMap_ActiveTasksMenu;
        public struct NewActionMapActions
        {
            private @NewControls m_Wrapper;
            public NewActionMapActions(@NewControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_NewActionMap_Movement;
            public InputAction @MouseLook => m_Wrapper.m_NewActionMap_MouseLook;
            public InputAction @SimpleShoot => m_Wrapper.m_NewActionMap_SimpleShoot;
            public InputAction @AlternativeShoot => m_Wrapper.m_NewActionMap_AlternativeShoot;
            public InputAction @ActiveFlashlight => m_Wrapper.m_NewActionMap_ActiveFlashlight;
            public InputAction @ReloadGun => m_Wrapper.m_NewActionMap_ReloadGun;
            public InputAction @ChangeWeapon => m_Wrapper.m_NewActionMap_ChangeWeapon;
            public InputAction @ActiveTasksMenu => m_Wrapper.m_NewActionMap_ActiveTasksMenu;
            public InputActionMap Get() { return m_Wrapper.m_NewActionMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(NewActionMapActions set) { return set.Get(); }
            public void SetCallbacks(INewActionMapActions instance)
            {
                if (m_Wrapper.m_NewActionMapActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnMovement;
                    @MouseLook.started -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnMouseLook;
                    @MouseLook.performed -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnMouseLook;
                    @MouseLook.canceled -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnMouseLook;
                    @SimpleShoot.started -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnSimpleShoot;
                    @SimpleShoot.performed -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnSimpleShoot;
                    @SimpleShoot.canceled -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnSimpleShoot;
                    @AlternativeShoot.started -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnAlternativeShoot;
                    @AlternativeShoot.performed -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnAlternativeShoot;
                    @AlternativeShoot.canceled -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnAlternativeShoot;
                    @ActiveFlashlight.started -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnActiveFlashlight;
                    @ActiveFlashlight.performed -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnActiveFlashlight;
                    @ActiveFlashlight.canceled -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnActiveFlashlight;
                    @ReloadGun.started -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnReloadGun;
                    @ReloadGun.performed -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnReloadGun;
                    @ReloadGun.canceled -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnReloadGun;
                    @ChangeWeapon.started -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnChangeWeapon;
                    @ChangeWeapon.performed -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnChangeWeapon;
                    @ChangeWeapon.canceled -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnChangeWeapon;
                    @ActiveTasksMenu.started -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnActiveTasksMenu;
                    @ActiveTasksMenu.performed -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnActiveTasksMenu;
                    @ActiveTasksMenu.canceled -= m_Wrapper.m_NewActionMapActionsCallbackInterface.OnActiveTasksMenu;
                }
                m_Wrapper.m_NewActionMapActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @MouseLook.started += instance.OnMouseLook;
                    @MouseLook.performed += instance.OnMouseLook;
                    @MouseLook.canceled += instance.OnMouseLook;
                    @SimpleShoot.started += instance.OnSimpleShoot;
                    @SimpleShoot.performed += instance.OnSimpleShoot;
                    @SimpleShoot.canceled += instance.OnSimpleShoot;
                    @AlternativeShoot.started += instance.OnAlternativeShoot;
                    @AlternativeShoot.performed += instance.OnAlternativeShoot;
                    @AlternativeShoot.canceled += instance.OnAlternativeShoot;
                    @ActiveFlashlight.started += instance.OnActiveFlashlight;
                    @ActiveFlashlight.performed += instance.OnActiveFlashlight;
                    @ActiveFlashlight.canceled += instance.OnActiveFlashlight;
                    @ReloadGun.started += instance.OnReloadGun;
                    @ReloadGun.performed += instance.OnReloadGun;
                    @ReloadGun.canceled += instance.OnReloadGun;
                    @ChangeWeapon.started += instance.OnChangeWeapon;
                    @ChangeWeapon.performed += instance.OnChangeWeapon;
                    @ChangeWeapon.canceled += instance.OnChangeWeapon;
                    @ActiveTasksMenu.started += instance.OnActiveTasksMenu;
                    @ActiveTasksMenu.performed += instance.OnActiveTasksMenu;
                    @ActiveTasksMenu.canceled += instance.OnActiveTasksMenu;
                }
            }
        }
        public NewActionMapActions @NewActionMap => new NewActionMapActions(this);
        public interface INewActionMapActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnMouseLook(InputAction.CallbackContext context);
            void OnSimpleShoot(InputAction.CallbackContext context);
            void OnAlternativeShoot(InputAction.CallbackContext context);
            void OnActiveFlashlight(InputAction.CallbackContext context);
            void OnReloadGun(InputAction.CallbackContext context);
            void OnChangeWeapon(InputAction.CallbackContext context);
            void OnActiveTasksMenu(InputAction.CallbackContext context);
        }
    }
}
